apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://decision_making_app.loki:3100
    basicAuth: false
    isDefault: true
    editable: true
    orgId: 1
    version: 1
    jsonData:
      timeInterval: 15s
